// Package sliceoapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package sliceoapi

// Error defines model for Error.
type Error struct {
	Message *string `json:"message,omitempty"`
}

// SliceParams defines model for SliceParams.
type SliceParams struct {
	Alpha       float32 `json:"alpha"`
	HopSize     int32   `json:"hopSize"`
	Id          *string `json:"id,omitempty"`
	InputPath   string  `json:"inputPath"`
	MaxSilKept  int32   `json:"maxSilKept"`
	MinInterval int32   `json:"minInterval"`
	MinLength   int32   `json:"minLength"`
	NParts      int32   `json:"nParts"`
	OutputRoot  string  `json:"outputRoot"`
	Threshold   float32 `json:"threshold"`
	XMax        int32   `json:"xMax"`
}

// SliceRequest defines model for SliceRequest.
type SliceRequest struct {
	CustomerId  string        `json:"customer_id"`
	SliceParams []SliceParams `json:"slice_params"`
}

// PostPreprocessCustomerIdSliceJSONRequestBody defines body for PostPreprocessCustomerIdSlice for application/json ContentType.
type PostPreprocessCustomerIdSliceJSONRequestBody = SliceRequest
